-- Seed Event Series with venue history
-- First, let's get venue IDs and create the series

-- Ultra Miami (venue changed in 2012)
INSERT INTO public.event_series (name, typical_month, typical_duration_days, first_year, description)
VALUES 
  ('Ultra Music Festival', 3, 3, 1999, 'Premier electronic music festival in Miami'),
  ('Electric Daisy Carnival Las Vegas', 5, 3, 2011, 'Largest electronic dance music festival in North America'),
  ('Electric Daisy Carnival Orlando', 11, 2, 2011, 'East coast edition of EDC'),
  ('Tomorrowland', 7, 3, 2005, 'Legendary Belgian electronic music festival'),
  ('Electric Forest', 6, 4, 2011, 'Unique forest festival in Michigan'),
  ('Movement Detroit', 5, 3, 2006, 'Techno festival in Detroit'),
  ('Electric Zoo', 9, 3, 2009, 'NYC electronic music festival'),
  ('Coachella', 4, 3, 1999, 'Iconic California desert festival'),
  ('Lollapalooza', 8, 4, 1991, 'Multi-genre festival in Chicago'),
  ('Lost Lands', 9, 3, 2017, 'Bass music festival in Ohio'),
  ('Bonnaroo', 6, 4, 2002, 'Multi-genre festival in Tennessee'),
  ('Outside Lands', 8, 3, 2008, 'San Francisco music festival'),
  ('Life Is Beautiful', 9, 3, 2013, 'Downtown Las Vegas festival'),
  ('III Points', 10, 3, 2013, 'Miami art and music festival'),
  ('CRSSD', 3, 2, 2015, 'San Diego waterfront festival'),
  ('Day Zero', 1, 1, 2012, 'Jungle festival in Tulum'),
  ('Escape Halloween', 10, 2, 2011, 'Insomniac Halloween festival'),
  ('Beyond Wonderland', 3, 2, 2010, 'SoCal Insomniac festival'),
  ('Nocturnal Wonderland', 9, 2, 1995, 'Original Insomniac festival'),
  ('Hard Summer', 8, 2, 2008, 'LA area Hard Events festival'),
  ('Holy Ship', 1, 3, 2012, 'Cruise ship EDM festival'),
  ('Shambhala', 8, 4, 1998, 'Canadian transformational festival'),
  ('Burning Man', 8, 7, 1986, 'Nevada desert art and culture festival'),
  ('Dreamstate', 11, 2, 2015, 'Trance-focused Insomniac festival'),
  ('EDC Mexico', 2, 3, 2014, 'Mexican edition of EDC'),
  ('Countdown NYE', 12, 1, 2014, 'New Years Eve Insomniac event'),
  ('Spring Awakening', 6, 3, 2012, 'Chicago electronic festival'),
  ('Imagine Festival', 9, 4, 2014, 'Atlanta electronic festival'),
  ('Something Wicked', 10, 2, 2012, 'Houston Halloween festival'),
  ('Decadence', 12, 2, 2012, 'NYE festival in Denver'),
  ('Global Dance Festival', 7, 2, 2007, 'Denver electronic festival'),
  ('Okeechobee', 3, 4, 2016, 'Florida multi-genre festival'),
  ('Hangout Fest', 5, 3, 2010, 'Gulf Shores Alabama beach festival'),
  ('Camp Bisco', 7, 3, 2004, 'Disco Biscuits festival in PA'),
  ('North Coast', 9, 3, 2010, 'Chicago Labor Day festival'),
  ('Moonrise', 8, 2, 2014, 'Baltimore electronic festival'),
  ('Firefly', 6, 4, 2012, 'Delaware multi-genre festival'),
  ('Paradiso', 6, 2, 2012, 'PNW festival at the Gorge'),
  ('Bass Canyon', 8, 3, 2018, 'Excision festival at the Gorge'),
  ('Freaky Deaky', 10, 2, 2015, 'Texas Halloween festival'),
  ('Veld', 8, 2, 2012, 'Toronto electronic festival'),
  ('Digital Dreams', 7, 2, 2013, 'Toronto waterfront festival'),
  ('Ever After', 6, 3, 2014, 'Canadian festival in Kitchener'),
  ('Seasons Festival', 2, 2, 2015, 'Vancouver winter festival'),
  ('Contact Festival', 12, 2, 2012, 'Vancouver NYE festival'),
  ('ADE', 10, 5, 1996, 'Amsterdam Dance Event'),
  ('Mysteryland', 8, 3, 1993, 'Dutch festival (also had USA edition)'),
  ('Awakenings', 6, 2, 1997, 'Amsterdam techno festival'),
  ('Time Warp', 4, 1, 1994, 'German techno event'),
  ('Defqon.1', 6, 3, 2003, 'Dutch hardstyle festival');